"""
Arena Cookie Extractor — Chạy trên máy có browser (desktop/laptop).

Cách dùng:
  1. Cài playwright:  pip install playwright && playwright install chromium
  2. Chạy script:     python3 extract_cookie.py
  3. Browser sẽ mở → đăng nhập Arena.ai (Google/GitHub)
  4. Script tự detect cookie và lưu vào .env

Hoặc copy cookie thủ công từ browser DevTools:
  - F12 → Application → Cookies → arena.ai
  - Copy giá trị arena-auth-prod-v1
  - Paste vào .env: ARENA_AUTH_COOKIE=<value>
"""

import asyncio
import sys


async def main():
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        print("❌ Chưa cài playwright. Chạy:")
        print("   pip install playwright")
        print("   playwright install chromium")
        sys.exit(1)

    async with async_playwright() as p:
        # Dùng headless=False để mở browser thật
        browser = await p.chromium.launch(
            headless=False,
            args=["--start-maximized"],
        )
        context = await browser.new_context(
            no_viewport=True,
        )
        page = await context.new_page()

        print("🌐 Đang mở arena.ai...")
        await page.goto("https://arena.ai/chat")

        print("\n" + "=" * 50)
        print("📋 HƯỚNG DẪN:")
        print("   1. Đăng nhập Arena.ai (Google/GitHub/Email)")
        print("   2. Đợi trang chat load xong")
        print("   3. Script sẽ tự detect cookie")
        print("=" * 50)

        arena_auth = None
        cf_clearance = None
        attempts = 0

        while attempts < 120:  # đợi tối đa 2 phút
            await asyncio.sleep(1)
            attempts += 1

            cookies = await context.cookies()
            for c in cookies:
                if c["name"] == "arena-auth-prod-v1" and c["value"]:
                    arena_auth = c["value"]
                if c["name"] == "cf_clearance" and c["value"]:
                    cf_clearance = c["value"]

            if arena_auth:
                print(f"\n✅ Tìm thấy arena-auth-prod-v1!")
                break

            if attempts % 10 == 0:
                print(f"   ⏳ Đang chờ đăng nhập... ({attempts}s)")

        if not arena_auth:
            print("\n❌ Không tìm thấy cookie sau 2 phút.")
            print("   Hãy đảm bảo đã đăng nhập thành công trên Arena.ai")
            await browser.close()
            return

        # Lưu vào .env
        env_content = f"""# Arena cookies (auto-extracted)
# Generated by extract_cookie.py
ARENA_AUTH_COOKIE={arena_auth}
CF_CLEARANCE={cf_clearance or ""}
"""
        with open(".env", "w") as f:
            f.write(env_content)

        print(f"\n{'=' * 50}")
        print("✅ Đã lưu cookie vào .env!")
        print(f"   arena-auth: {arena_auth[:30]}...")
        print(f"   cf_clearance: {(cf_clearance or 'N/A')[:30]}...")
        print(f"\n🚀 Chạy server:  python3 main.py")
        print(f"{'=' * 50}")

        await browser.close()


if __name__ == "__main__":
    asyncio.run(main())
